[tools]
go = "1.26"
"go:github.com/daixiang0/gci" = "latest"
"github:golangci/golangci-lint" = "latest"
"github:securego/gosec" = "latest"
"github:goreleaser/goreleaser" = "latest"

[env]
CGO_ENABLED=0

[tasks.vendor]
description = "Vendor resets the main module's vendor directory to include all packages needed to build the application"
run = "go mod vendor"

[tasks.tidy]
description = "Tidy makes sure go.mod matches the source code in the module"
run = "go mod tidy"

[tasks.build]
description = "Build the application"
run = "goreleaser build --clean --snapshot"
depends = ["vendor"]

[tasks."lint"]
depends = ["lint:go", "lint:goreleaser"]

[tasks."lint:go"]
description = "Linting automatically checks code for errors and style issues"
run = "golangci-lint run"

[tasks."lint:goreleaser"]
description = "Run a goreleaser check"
run = "goreleaser check"

[tasks.test]
description = "Checks to verify code correctness"
run = "go test -cover ./..."
depends = ["vendor"]

[tasks.release]
description = "Build and publish AMD64 and ARM64 lambda-handler.zip releases via goreleaser"
run = "goreleaser release"
depends = ["vendor"]

[tasks."snapshot"]
description = "Build AMD64 and ARM64 lambda-handler.zip artifacts locally without publishing"
run = "goreleaser release --clean --snapshot"
depends = ["vendor"]

