name: 📋 Lint

on:
  push

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v6

      - name: 📦 Install Mise
        uses: jdx/mise-action@v4

      - name: 📋 Lint
        run: mise run lint
