name: Publish

on:
  push:
    tags:
      - v*

jobs:
  artifacts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v6

      - name: 📦 Install Mise
        uses: jdx/mise-action@v4

      - name: ☁️ Release
        run: mise run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

