name: Snapshot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v6

      - name: 📦 Install Mise
        uses: jdx/mise-action@v4

      - name: 🧪 Test
        run: mise run snapshot
